### ISSUE TITLE
plugin is not working

### ISSUE THREAD

**Issue by L3sh44** [Stimayk/AdminSessionLog#1]
CSSharp v235
Meta 1293
DU 2.0.4 

DU working.
But adminsessionlog not working and spaming error :
2024-05-26 02:40:48.085 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void DiscordUtilitiesAPI.IDiscordUtilitiesAPI.SendCustomMessageToChannel(System.String, UInt64, System.String, Builder, Builder)'.
   at AdminSessionLog.AdminSessionLog.PlayerConnect(EventPlayerConnectFull event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by Stimayk** [comment]
Fixed

**Comment by L3sh44** [comment]
anyway not working 
2024-05-27 01:52:16.342 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void DiscordUtilitiesAPI.IDiscordUtilitiesAPI.SendCustomMessageToChannel(System.String, UInt64, System.String, Builder, Builder)'.
   at AdminSessionLog.AdminSessionLog.PlayerConnect(EventPlayerConnectFull event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by L3sh44** [comment]
"AdminSessionLog" (v1.0.3) by E!N 
cfg 
{
  "DiscordChannelId": 1244062634077327464,
  "AdminFlag": [
    "@css/reservation",
    "@css/generic",
    "@css/kick",
    "@css/ban",
    "@css/unban",
    "@css/vip",
    "@css/slay",
    "@css/changemap",
    "@css/cvar",
    "@css/config",
    "@css/chat",
    "@css/vote",
    "@css/password",
    "@css/rcon",
    "@css/cheats",
    "@css/root"
  ],
  "AllowConnectMessage": true
}

**Comment by Erik-97** [comment]
I got the same error

Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void DiscordUtilitiesAPI.IDiscordUtilitiesAPI.SendCustomMessageToChannel(System.String, UInt64, System.String, Builder, Builder)'.
   at AdminSessionLog.AdminSessionLog.PlayerConnect(EventPlayerConnectFull event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

Plugins used:
DiscordUtilities
DU_ChatRelay
DU_EventNotifications
DU_Report
DU_ServerStatus
